### ISSUE TITLE
Update templates to match the 4.0.0 release (Strade Bianchi)

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument-cli#48]
There will be quite a few changes the main one so far is around the default config object and some basic changes there. 

Will add more comments with additional things as it progresses.

The project can be tracked here: https://github.com/ansble/monument/projects/1

And related tickets can be found here: https://github.com/ansble/monument/milestone/13

**Comment by janga1997** [comment]
@designfrontier I would like to work on this issue too. Any tips?

**Comment by designfrontier** [comment]
So this one will have some changes to the config that is laid down and a couple other things depending on what actually lands in the 3.0.0 release. Keeping an eye on  https://github.com/ansble/monument/pull/306 will help

**Comment by fullstackguyhere** [comment]
hi @designfrontier I would like work on this issue. I am guessing this is still open?
