### ISSUE TITLE
refactor `finalName` in newRoute.js

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument-cli#55]
It should be assigned a value from a function so that it can be a const. There isn't a reason to have it be a let other then all the logic to do its assignment. So move that logic into a function that returns the correct value.

Then move 
```
targetTestPath,
targetPath,
chalkedFileName
```

to `const` as well. They are only where they are because of finalName

**Comment by xingwang** [comment]
See if that works for you.

**Comment by designfrontier** [comment]
left you a single request for revisions... thanks this looks fantastic!

**Comment by xingwang** [comment]
Done :)
