### ISSUE TITLE
lock down dependencies

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument-cli#91]
Remove any `~` or `>` or `^` from the dependencies in the package.json file. This will help with stability long term.

Also add an npm lock file for npm > 5

**Comment by renatoselenica** [comment]
Can I help with this one?

**Comment by renatoselenica** [comment]
Well looks like people got to it. :D

**Comment by designfrontier** [comment]
closed by https://github.com/ansble/monument-cli/pull/95
